# Generated by Django 6.0.4 on 2026-04-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagetree', '0002_delete_testblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='base_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False,
                verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='css_extra',
            field=models.CharField(
                blank=True, help_text='extra CSS classes (space separated)',
                max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False,
                verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='deep_toc',
            field=models.BooleanField(
                default=False,
                help_text='include children of children in TOC. ' +
                '(this only makes sense if the above is checked)'
            ),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False,
                verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='show_toc',
            field=models.BooleanField(
                default=False,
                help_text='list table of contents of immediate child ' +
                'sections (if applicable)'
            ),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False,
                verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='path',
            field=models.CharField(default='/', max_length=256),
        ),
        migrations.AlterField(
            model_name='userpagevisit',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False,
                verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userpagevisit',
            name='status',
            field=models.CharField(default='incomplete', max_length=256),
        ),
        migrations.AlterField(
            model_name='version',
            name='activity',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='data',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False,
                verbose_name='ID'),
        ),
    ]
